### ISSUE TITLE
Enable Travis support in VoodooInput

### ISSUE THREAD

**Issue by vit9696** [acidanthera/VoodooInput#4]
We would like to build with CI enabled, so that the releases are uploaded automatically. Also, for simplicity of release making I wonder if VoodooInput should be moved to @acidanthera or @alexandred.

**Comment by kprinssu** [comment]
Honestly, this is somewhat indepedent of VoodooI2C. There's a couple of things I do would like to see before this project is moved into @acidanthera:

- a proper license (I am very much against this project being used in any commercial projects/ventures and would prefer GNU AGPLv3)
- a README with proper accrediation to everyone who worked on reverse engineering

Additionally, I would like to get @alexandred opinion on moving the project into @acidanthera.

**Comment by vit9696** [comment]
@kprinssu, this sounds fine to me:

* As for the license I request BSD 3-clause or any similar license. Prohibiting free projects like FreeBSD to use this code is discrimination. Putting aside my opinion, we cannot accept GPLv3 or alike as it may not let us contribute to this project in the future. We may agree with GPLv2 if absolutely necessary, but it is strange to believe it will stop any person from ignoring it or that in fact there is any interested party in it.
* As for README, I can create it in the nearest future, but we would like to hear a word or two from VoodooI2C team.

**Comment by kprinssu** [comment]
As VoodooI2C is licensed as GPLv2 and since VoodooInput reuses code from VoodooI2C, VoodooInput should also be licensed as GPLv2 (as it is a derivative work).

For the VoodooI2C team, I'll ping the necessary members: @alexandred @ben9923 @blankmac @coolstar

**Comment by vit9696** [comment]
Alright, done with both. README may want further touches though. Sorry if I missed anybody.

**Comment by blankmac** [comment]
I was a minor player at best with respect to the code in VoodooI2C etc.  I will defer to the others with respect to the repo’s resting place and licensing.

**Comment by kprinssu** [comment]
Ownership of the repo is now under @acidanthera.
